### ISSUE TITLE
Questions about the table on the last page of the PDF with the game's instructions

### ISSUE THREAD

**Issue by denizakcal** [powergrid-comp-345/PowerGrid#5]
1) That's for how many of each resource token is returned to the supply at the end of fifth "phase" (pdf's terminology) of the current "step" (pdf's terminology), right?

2) **Is that in any way related to how many resources each player consumes in (the fifth "phase" (pdf's terminology) of) any given "step" (pdf's terminology)?**

P.S.
I tried to upload the file here (for your convenience), but there was a problem. Sorry about that.

**Comment by RoseDuf** [comment]
1. Yes, it's at the end of each round, its a table that explains how to restock the resources depending on how many players are playing

2. No, it doesn't necessarily have to do with any of the steps per say. We do it when finishing phase 5. after earning cash (bureaucracy phase).

Bureaucracy phase:
1-Use resources to power cities
2-Players earn cash
3-Restock resources (according to the table in the instructions)

**Comment by denizakcal** [comment]
Thanks, but I'm still a little unclear.

Basically, what if all the players decide to keep / not use their resources (even if it's not in their best interest)? Where would the tokens for resupplying come from?

**Comment by RoseDuf** [comment]
I doesn't depend on whether or not people use their resources. It always restocks if there is any available resources (so this could come from the bag of resources)

**Comment by denizakcal** [comment]
So, in the real board game, there are enough tokens to populate the entire supply as well as all six players' four power plants?

**Comment by RoseDuf** [comment]
If there is no available resources left, then nothing gets restocked lol

**Comment by RoseDuf** [comment]
Basically when people use their resources, it goes automatically into the "resources bag" and when its time to restock, the game will restock from the "resource bag" (if there are available resources available)

**Comment by denizakcal** [comment]
So, that table serves as an **upper bound** of how many of each resource tokens to restock?

For example, if there's one oil in the "resource bag", but the table says two oils, then one oil gets restocked?

And, similarly, if there's three oils in the "resource bag", but the table says two oils, then two oils get restocked, with one oil remaining in the "resource bag" for a future restocking (in the next "step")?

**Comment by RoseDuf** [comment]
Yes exactly

**Comment by denizakcal** [comment]
Okay, great! :D Thanks for clarifying!

(I'm closing this issue now.)
